---
- hosts: fortigate
  collections:
  - fortinet.fortios
  connection: httpapi
  tasks:
  - name: gather basic system info and physical interface port3 status facts
    fortios_facts:
      vdom:  "{{ vdom }}"
      gather_subset:
        #  - fact: 'system_current-admins_select'
        - fact: 'system_firmware_select'
        #  - fact: 'system_fortimanager_status'
        #  - fact: 'system_ha-checksums_select'
        - fact: 'system_interface_select'
          filters:
            - interface_name: 'port1'
        #  - fact: 'system_status_select'
        - fact: 'system_time_select'
